name: Semantic Dreamer
favicon: null
layout_spectrum: 0.1264264569617808
typography_spectrum: 0.16713840258307755
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9929082123562694
  lightness: 0.39350131270475686
  saturation: 0.5863595092669129
  rhythmicContrast: 0.4738997973036021
purpose: []
